# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxdemo', '0002_auto_20180531_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
